Include hacking `.md` inside `cargo doc` output
massalabs/massa pull request #1905
Opened 2021-12-03 09:19 UTC by yvan-sraka

2021-12-03 09:39 UTC, AureliaDolo reviewed
What happened with the indentation? There are plenty of extra spaces all over

2021-12-03 09:39 UTC, AureliaDolo commented on consensus/pos.md
> +1. use the initial (genesis) roll registry as the roll count source
Wrong indentation

2021-12-03 09:39 UTC, AureliaDolo commented on consensus/pos.md
> +1. `sha256^N(cfg.initial_draw_seed)` as the seed, where `sha256^N` means that we apply the sha256 hash function N times consecutively
Wrong indentation

2021-12-03 09:39 UTC, AureliaDolo commented on consensus/pos.md
> +1. force the draw outcome to match the genesis creator's address to keep draws consistent
Wrong indentation

2021-12-06 12:59 UTC, AureliaDolo requested changes
There is a pos.md in massa_consensus and in consensus

2021-12-06 12:59 UTC, AureliaDolo commented on consensus/endorsements.md
> +-   `1/(1 + config.endorsement_count)` to the block creator
Why did you add indentation here ?

2021-12-06 12:59 UTC, AureliaDolo commented on consensus/endorsements.md
> +-   addresses A, B, C in thread 0
same question on indentation

2021-12-06 12:59 UTC, AureliaDolo commented on consensus/endorsements.md
> +-   the part that goes to A is :
same

2021-12-06 12:59 UTC, AureliaDolo commented on consensus/pos.md
> +-   `cycle_states: Vec<VecDeque<ThreadCycleState>>` indices: `[thread][cycle] -> ThreadCycleState`
why indentation ?

2021-12-06 12:59 UTC, AureliaDolo commented on consensus/pos.md
> +1. use the initial (genesis) roll registry as the roll count source
that wasn't solved !

2021-12-06 12:59 UTC, AureliaDolo commented on docs/api.md
> -String // Block id
From what I recall it must be in an array

2021-12-06 13:32 UTC, adrien-zinger commented on consensus/endorsements.md
> +-   creators: the ordered addresses that were selected to create endorsements in for that slot
What is the justification of all this alignments diffs?

2021-12-06 13:34 UTC, adrien-zinger commented on consensus/endorsements.md
> +-   creators: the ordered addresses that were selected to create endorsements in for that slot
duplications..

2021-12-06 22:20 UTC, yvan-sraka commented on consensus/endorsements.md
> +-   `1/(1 + config.endorsement_count)` to the block creator
Default .md formating

2021-12-06 22:32 UTC, yvan-sraka commented
https://dprint.dev/ is used as default formater that's why the indentation

2021-12-07 08:13 UTC, AureliaDolo requested changes

2021-12-07 08:13 UTC, AureliaDolo commented on consensus/pos.md
> +2. `sha256^N(cfg.initial_draw_seed)` as the seed, where `sha256^N` means that we apply the sha256 hash function N times consecutively
Wrong identation

2021-12-07 08:13 UTC, AureliaDolo commented on consensus/pos.md
> +    2. deactivate all candidate rolls for all addresses for which `cycle_states[Tau][1 + lookback_cycles].production_stats[address].(.0 / (.0 + .1)) > cfg.pos_miss_rate_deactivation_threshold`
wrong indentation

2021-12-07 08:26 UTC, AureliaDolo commented
That may me a dumb question, but why didn't you just keep the formatting as it was ?

2021-12-07 09:32 UTC, AureliaDolo requested changes

2021-12-07 09:32 UTC, AureliaDolo commented on consensus/pos.md
> +6. deactivate all candidate rolls for all addresses for which `cycle_states[Tau][1 + lookback_cycles].production_stats[address].(.0 / (.0 + .1)) > cfg.pos_miss_rate_deactivation_threshold`
aarrggpaaaaifezfez I did not saw this one

2021-12-07 09:43 UTC, AureliaDolo approved these changes

2021-12-07 09:47 UTC, AureliaDolo commented
Bors merge

2021-12-07 10:02 UTC, AureliaDolo approved these changes

2021-12-07 10:02 UTC, AureliaDolo commented
bors merge

2021-12-07 10:08 UTC, yvan-sraka commented
bors merge

2021-12-07 10:12 UTC, yvan-sraka commented
bors merge

2021-12-07 10:23 UTC, yvan-sraka commented
bors merge

2021-12-07 10:31 UTC, AureliaDolo commented
bors merge

2021-12-07 10:53 UTC, yvan-sraka commented
bors merge

2021-12-07 10:54 UTC, merged