Standardize crate name with `massa_` prefix
massalabs/massa pull request #1920
Opened 2021-12-06 08:26 UTC by yvan-sraka

2021-12-06 08:34 UTC, AureliaDolo commented on Cargo.toml
>      "time",
time too can be renamed, and rename UTime to MassaTime, I guess

2021-12-06 09:53 UTC, AureliaDolo approved these changes

2021-12-06 09:53 UTC, AureliaDolo requested changes
Doctests are not ok

2021-12-06 12:51 UTC, AureliaDolo reviewed
I'm quite not sure about removing indentations in config.toml

2021-12-06 13:29 UTC, adrien-zinger commented
![image](https://user-images.githubusercontent.com/7893775/144854338-0fc5ebe7-a59c-4463-8cba-60693aab32c1.png)
>*"when everyone's massa, no one will be"* - Syndrom

2021-12-06 14:20 UTC, AureliaDolo commented
Oh no, conflicts :crossed_swords:

2021-12-06 22:34 UTC, yvan-sraka commented
I will wait for https://github.com/massalabs/massa/pull/1848 to be merged first in intend of not playing solving conflict twice!

2021-12-07 08:14 UTC, AureliaDolo commented
> I will wait for #1848 to be merged first in intend of not playing solving conflict twice!

What's the link with #1848 ?

2021-12-07 13:17 UTC, AureliaDolo commented
@yvan-sraka aaand conflicts (and failed doc tests) :cry:

2021-12-08 11:01 UTC, yvan-sraka commented
> Doctests are not ok

@AureliaDolo solved!

2021-12-08 11:12 UTC, AureliaDolo approved these changes

2021-12-08 11:12 UTC, AureliaDolo commented
bors merge

2021-12-08 13:22 UTC, yvan-sraka commented
bors merge

2021-12-08 13:57 UTC, AureliaDolo approved these changes

2021-12-08 13:58 UTC, yvan-sraka commented
bors merge

2021-12-08 16:44 UTC, adrien-zinger approved these changes

2021-12-08 16:53 UTC, adrien-zinger approved these changes

2021-12-08 16:54 UTC, yvan-sraka commented
bors merge

2021-12-08 16:59 UTC, adrien-zinger approved these changes

2021-12-08 16:59 UTC, yvan-sraka commented
bors merge

2021-12-09 15:27 UTC, AureliaDolo approved these changes

2021-12-09 15:31 UTC, yvan-sraka commented
bors merge

2021-12-09 15:46 UTC, merged