Temporary set a version of rust
massalabs/massa pull request #2141
Opened 2022-01-12 15:44 UTC by adrien-zinger

Set a version temporary, waiting for a nightly release compatible.
Version rustc: 1.59.0

> If you see this commit in a month and it's not already revert, try to revert it quick!

2022-01-12 15:49 UTC, AureliaDolo approved these changes

2022-01-12 15:53 UTC, AureliaDolo commented
> > If you see this commit in a month and it's not already revert, try to revert it quick!

see #2142

2022-01-12 15:54 UTC, AureliaDolo commented
bors merge

2022-01-12 16:15 UTC, AureliaDolo commented
@damip and mcos is failling again with test_roll_block_creation

2022-01-13 10:49 UTC, damip commented
let's ALSO disable the problematic test in this PR and open a special issue for corrrecting it

2022-01-13 11:48 UTC, damip requested changes
let's also disable the problematic test in this PR and open an issue for corrrecting it

2022-01-13 13:18 UTC, yvan-sraka commented
Could we ensure that this PR will be reverted soon? Could we link here the `rustc` issue that we wait to be solved?

2022-01-13 14:12 UTC, AureliaDolo commented
see #2142 for follow up

2022-01-13 19:53 UTC, merged