Update config doc.
massalabs/massa pull request #2200
Opened 2022-01-20 16:25 UTC by AureliaDolo

Fix #1377

2022-01-20 16:27 UTC, AureliaDolo commented
@Noxhaa If you wanna take a look, so you might help people adjust their config to maybe have better stability

2022-01-21 12:53 UTC, Noxhaa commented
Nice comments, it will help for sure !

2022-01-21 13:36 UTC, damip requested changes

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # increase for more info about the node. May reduce your node ability to keep up with the network
Logging level. High log levels might impact performance. 0: ERROR, 1: WARN, 2: INFO, 3: DEBUG, 4: TRACE

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # where to send admin level requests (node management)
address:port on which the node API listens for admin and node management requests. Dangerous if publicly exposed.

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # where to send public requests (get data, send operation)
address:port on which the node API listens for public requests. Can be exposed to the Internet.

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number items accepted
max number of arguments per RPC call

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # path to the initial sequential balance ledger
path to the initial smart contract balance ledger

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # if a block  is future_block_processing_max_periods periods in the future, it is just discarded
...at least future_block_processing_max_periods in the future...

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # number of final periods that must be kept at all time (increse to more resilience to short network disconnections)
at all times

increase for more resilience

. High values will increase RAM usage.

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of time the node tries to fill up a block before producing it
max number of batches of pool operations to scan when generating a block

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # number of operation to include in a block
size of a pool operation batch for block creation

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # path to the cold sored ledger
path to the ledger file

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # wether to overwrite the ledger at start
whether

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # path to the initial ledger
path to the initial consensus balance ledger

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # number of cached cycle for proof of stake seed initialization
number of cycles cached by the proof-of-stake selection system

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number for the local vision of what blocks a node knows
max cache size for which blocks a foreign node knows about

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number for the local vision of what blocks a node wants
max cache size for which blocks a foreign node asked for

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of blocks we can asked per node
asked => ask simultaneously

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number for the local vision of what operations a node knows
max cache size for which operations a foreign node knows about

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number for the local vision of what endorsements a node knows about
max cache size for which endorsements a foreign node knows about

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # where to listen for communication
address:port on which to listen for protocol communication

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # millis spent waiting for a respone
timeout for connection establishment

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # connection attempt to avaible peers every wakeup_interval millis
attempt a connection to available peers when needed every wakeup_interval milliseconds

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # path to the cold stored peers
path to the local peers storage file

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # path to the initial peer file
peers

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # target number of connection to a bootstrap node, once the bootstrap succeeded
number of connections to bootstrap nodes

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of connection attempts to bootstrap nodes, once the bootstrap succeeded
max number of simultaneous protocol connection attempts towards bootstrap nodes

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # target number of non bootstrap out connections
out => outgoing

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of in non bootstrap connections
in => inbound

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of in connections per ip
in => inbound

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of out non bootstrap connection attempts
out => outgoing

simultaneous

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # peers are cold stored every peers_file_dump_interval millis
cold stored => dumped to file

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # after message_timeout millis we are no longer waiting on handshake message
timeout when waiting for a message from a foreign node

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # Every ask_peer_list_interval in millis we ask every one for its advertisable peers list.
interval in milliseconds for asking peer lists from peers we are connected to

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of operation per message
operations

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # we forget we banned a node after ban_timeout
milliseconds

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # list of bootstrap (ip, public key)
public key => node ID

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # [optionnal] for bootstrap servers to port people will bootstrap from
[optional] address:port on which to listen for incoming bootstrap requests

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # delay before an other bootsrap attempt
delay in milliseconds to wait between consecutive bootstrap attempts

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # if ping is too high bootstrap will be inturrupted
milliseconds

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # after read timeout millis, we stop reading
timeout for incoming message readout

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # after write_timeout millis, we stop writing
timeout for message sending

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # if enabled, time will be synchronized on the server time
when enabled, apply a correction to the local computer clock to match bootstrap server time

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # [server] data is kept for cache duration millis
bootstrap data is cached for ...

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max size of recently bootstraped ips
max size of recently bootstrapped IP cache

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # after a botstrap attemp, a peer must wait per_ip_min_interval millis
refuse consecutive bootstrap attempts from a given IP when the interval between them is lower than per_ip_min_interval milliseconds

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of operation kept per thread
operations

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of endorsement kept
endorsements

2022-01-21 13:36 UTC, damip commented on massa-node/base_config/config.toml
> +    # max number of item returned per query
items

2022-01-26 11:13 UTC, damip requested changes
just a couple more

2022-01-26 14:16 UTC, damip approved these changes

2022-01-26 14:55 UTC, AureliaDolo commented
bors merge

2022-01-26 15:05 UTC, merged