Init testnet 20
massalabs/massa pull request #3498
Opened 2023-02-03 16:40 UTC by aoudiamoncef

* [ ] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

2023-02-13 14:46 UTC, AurelienFT requested changes

2023-02-13 14:48 UTC, aoudiamoncef commented on massa-execution-worker/src/interface_impl.rs
> +    fn hash_sha256(&self, bytes: &[u8]) -> Result<[u8; 32]> {
It was planned but I canceled It as there is no test for ABI's in massa core. May be it's time to create a dedicated tests file ?

2023-02-13 15:09 UTC, AurelienFT commented on massa-execution-worker/src/interface_impl.rs
> +    fn hash_sha256(&self, bytes: &[u8]) -> Result<[u8; 32]> {
Yes you can introduce some tests on the interface massa side

2023-02-13 17:39 UTC, aoudiamoncef commented on massa-node/base_config/gas_costs/abi_gas_costs.json
> +  "assembly_script_hash_sha256": 244,
Cool, I used the same value as the existing hashing function. 

Take a look at https://github.com/massalabs/massa-sc-runtime/issues/228

2023-02-13 22:24 UTC, aoudiamoncef commented on massa-execution-worker/src/interface_impl.rs
> +    fn hash_sha256(&self, bytes: &[u8]) -> Result<[u8; 32]> {
The test is trivial but I found the integration painful

```rust
#[test]
#[serial]
fn test_hash_sha256() {
	//THIS IS AVAILABLE ONLY in #[cfg(any(feature = "gas_calibration", feature = "benchmarking"))]
    let interface = InterfaceImpl::new_default(
        Address::from_str("AU12cMW9zRKFDS43Z2W88VCmdQFxmHjAo54XvuVV34UzJeXRLXW9M").unwrap(),
        None,
    );
    let actual_hash = interface.hash_sha256("something".as_bytes()).unwrap();
    let expected_hash =
        "3fc9b689459d738f8c88a3a48aa9e33542016b7a4052e001aaa536fca74813cb".as_bytes();
    assert_eq!(actual_hash, expected_hash);
}
```

If you have a better idea, I'll take it

2023-02-14 08:34 UTC, AurelienFT commented on massa-execution-worker/src/interface_impl.rs
> +    fn hash_sha256(&self, bytes: &[u8]) -> Result<[u8; 32]> {
You can add the testing feature to the list of feature gas_calibration and benchmarking

2023-02-14 10:52 UTC, AurelienFT commented on massa-node/base_config/gas_costs/abi_gas_costs.json
> +  "assembly_script_hash_sha256": 244,
I need to have this merged on testnet to run the gas-calib. Can you remove this change ? And I will fix the CI on testnet branch using our bot

2023-02-14 11:55 UTC, aoudiamoncef commented on massa-execution-worker/src/interface_impl.rs
> +    fn hash_sha256(&self, bytes: &[u8]) -> Result<[u8; 32]> {
thanks for the boost 👍🏻 . Tests are working let's gooo

2023-02-14 13:07 UTC, AurelienFT reviewed
Can you fix this two clippy lints ? https://github.com/massalabs/massa/actions/runs/4173498451/jobs/7226016090 and we are good to go for merging !

2023-02-14 13:24 UTC, aoudiamoncef commented
> Can you fix this two clippy lints ? [massalabs/massa/actions/runs/4173498451/jobs/7226016090](https://github.com/massalabs/massa/actions/runs/4173498451/jobs/7226016090) and we are good to go for merging !

I dont have any clippy smells with: `rustc 1.69.0-nightly (e972bc808 2023-01-29) && clippy 0.1.69 (e972bc80 2023-01-29)`

2023-02-14 14:36 UTC, aoudiamoncef commented
@AurelienFT it's valentine gift 💟 . the toolchain is up to date.

2023-02-14 14:44 UTC, AurelienFT approved these changes
Nice one !

2023-02-14 16:32 UTC, merged