Use upper_limit_ident instead of cycle + 1.
massalabs/massa pull request #4104
Opened 2023-06-19 06:38 UTC by Leo-Besancon

* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

2023-06-26 15:42 UTC, sydhds requested changes

2023-06-26 15:42 UTC, sydhds commented on massa-pos-exports/src/pos_final_state.rs
> +const UPPER_LIMIT: u8 = 255u8;
Why not using u8::MAX here?

2023-06-26 16:17 UTC, Leo-Besancon commented on massa-pos-exports/src/pos_final_state.rs
> +    fn test_pos_cache_recomputation() {
Added some comments, please tell me if it's easier to understand now ;)

2023-06-29 06:37 UTC, Leo-Besancon commented
@sydhds :)

2023-06-29 08:51 UTC, sydhds approved these changes

2023-06-29 08:51 UTC, merged