Allow local IPs, use same config flag for pre and post max_in_connections
massalabs/massa pull request #4116
Opened 2023-06-19 15:48 UTC by litchipi

PR in PeerNet: 

* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

2023-06-19 15:51 UTC, AurelienFT commented
Can you make your PR point to testnet_24 please

2023-06-23 08:18 UTC, litchipi commented
@modship @damip Assigning you for review as Aurelian is not available

2023-06-23 08:22 UTC, modship approved these changes
solve clippy and it's ok for me

2023-06-26 06:12 UTC, AurelienFT requested changes
Thank you for the clean up. I think there is other places where we use is_global that should be changed like [there](https://github.com/massalabs/massa/blob/b640980d15ce46b6dd25a29656e1c01158c04a8e/massa-protocol-worker/src/handlers/peer_handler/models.rs#L133) and in the tester of peer_handler. Search for all the `is_global()` call in the code and you should find everywhere you need to modify

2023-06-26 06:12 UTC, AurelienFT commented on massa-node/base_config/config.toml
> +    default_category_info = { target_out_connections = 10, max_in_connections_per_ip = 2, max_in_connections = 15}
It would be nice to take the boolean about the possibility to have local address to connect to us directly in the config there.

2023-06-28 09:33 UTC, litchipi commented
Actually the other `is_global` are skipped on purpose

In `massa-protocol-worker/src/handlers/peer_handler/models.rs`, in the function `get_rand_peers_to_send`, it makes no sense to send a local node to a remote peer, so the `is_global` filters well the peers here

In `massa-protocol-worker/src/handlers/peer_handler/tester.rs`, it doesn't make sense to test the local peer as it doesn't rely on the network (it's loopback)

What is the expected behaviour you were expecting in these cases ?

2023-06-30 08:02 UTC, AurelienFT approved these changes
Ok for me can you just test in labnet before merge plz

2023-06-30 13:30 UTC, litchipi commented
Seams to work like a charm :smiley:

2023-06-30 13:42 UTC, merged