fix doc client
massalabs/massa pull request #4414
Opened 2023-09-19 13:33 UTC by AurelienFT

Fix #4410

2023-09-19 15:42 UTC, sydhds requested changes

2023-09-19 15:42 UTC, sydhds commented on massa-sdk/src/config.rs
>      /// maximum size in bytes of a response.
Is this one correct?

2023-10-17 07:12 UTC, AurelienFT commented on massa-sdk/src/config.rs
>      /// maximum size in bytes of a response.
Fixed.

2023-10-17 12:36 UTC, sydhds approved these changes

2023-10-17 12:59 UTC, AurelienFT commented
bors merge

2023-10-17 14:32 UTC, merged