Add serde json tests
massalabs/massa pull request #4579
Opened 2023-12-04 15:02 UTC by aoudiamoncef

* [x] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

2023-12-07 10:00 UTC, sydhds requested changes

2023-12-07 10:09 UTC, aoudiamoncef commented on massa-models/src/amount.rs
> +        let expected_amount = Amount::from_str("11.111").unwrap();
Yes we could make the test more robust by adding more cases

2023-12-07 13:00 UTC, Leo-Besancon approved these changes, later dismissed

2023-12-07 13:57 UTC, aoudiamoncef commented on massa-models/src/block.rs
> +                denunciations: Vec::new(), // FIXME
I don't know, but may be use a real decounciation

2023-12-07 14:19 UTC, aoudiamoncef commented on massa-final-state/src/state_changes.rs
>          let serialized = serialized.unwrap();
done

2023-12-07 15:03 UTC, Leo-Besancon submitted a review, later dismissed

2023-12-08 08:31 UTC, sydhds requested changes

2023-12-08 13:20 UTC, aoudiamoncef commented on massa-models/src/datastore.rs
> +    struct SerdeWrapper(#[serde_as(as = "Vec<(_, _)>")] Datastore);
Are you sure, this could have breaking changes no ?

2023-12-08 13:22 UTC, aoudiamoncef commented on massa-models/src/amount.rs
> +        let expected_amount_3 = Amount::from_str("9999999999.999").unwrap();
It's little bit special in our case: 9_999_999_999.1_000_000_000 is the max accepted value

2023-12-08 13:25 UTC, aoudiamoncef commented on massa-models/src/operation.rs
> +    fn test_transaction_serde() {
IMHO,  KISS > DRY, we have separate tests

2023-12-08 13:31 UTC, aoudiamoncef commented on massa-models/src/amount.rs
> +        let expected_amount_3 = Amount::from_str("9999999999.999").unwrap();
done

2023-12-08 15:06 UTC, sydhds commented on massa-models/src/datastore.rs
> +    struct SerdeWrapper(#[serde_as(as = "Vec<(_, _)>")] Datastore);
With Deref & DerefMut trait implemented, it should not break many things I guess

2023-12-08 15:07 UTC, sydhds commented on massa-models/src/amount.rs
> +        let expected_amount_3 = Amount::from_str("9999999999.999").unwrap();
Maybe add a small comment to explain or point to a location where this maximum is explained?

2023-12-11 10:08 UTC, aoudiamoncef commented on massa-models/src/datastore.rs
> +    struct SerdeWrapper(#[serde_as(as = "Vec<(_, _)>")] Datastore);
@Leo-Besancon it's risky IMHO

2023-12-11 10:09 UTC, aoudiamoncef commented on massa-models/src/amount.rs
> +        let expected_amount_3 = Amount::from_str("9999999999.999").unwrap();
@damip could help us o this

2023-12-11 15:41 UTC, sydhds commented on massa-models/src/datastore.rs
> +    struct SerdeWrapper(#[serde_as(as = "Vec<(_, _)>")] Datastore);
Not sure to understand why this is risky... I should be fairly transparent with the Deref & DerefMut trait no?

2023-12-11 15:46 UTC, damip commented on massa-models/src/amount.rs
> +        let expected_amount_3 = Amount::from_str("9999999999.999").unwrap();
the maximal value for Amount is "18446744073.709551615"

2023-12-12 09:07 UTC, aoudiamoncef commented on massa-models/src/amount.rs
> +        let expected_amount_3 = Amount::from_str("9999999999.999").unwrap();
done

2023-12-12 13:28 UTC, sydhds commented on massa-models/src/datastore.rs
> +    struct SerdeWrapper(#[serde_as(as = "Vec<(_, _)>")] Datastore);
As it is used only in unit tests, it's alright

2023-12-12 13:28 UTC, sydhds approved these changes, later dismissed

2023-12-13 07:16 UTC, Leo-Besancon submitted a review, later dismissed

2023-12-13 07:16 UTC, Leo-Besancon commented on massa-models/src/amount.rs
> +/// The minimal value is 0 and the maximal value is 18446744073.709551615U(std::u64::MAX/1e9)
" " instead of "U"?

2023-12-13 08:05 UTC, sydhds approved these changes, later dismissed

2023-12-13 09:28 UTC, aoudiamoncef commented
@Leo-Besancon you can merge this without waiting for the CI

2023-12-13 14:35 UTC, Leo-Besancon approved these changes

2023-12-13 16:27 UTC, merged